export interface ICustomer {
  Id?: string;
  Name: string;
  Surname: string;
  TCNumber: string;
  PassportNumber: string;
  Gender: string;
  BirthDate: string;
  BirthPlace: string;
  BloodGroup: string;
  MotherName?: string;
  FatherName?: string;
  FirstPhone: string;
  EmergencyPhone?: string;
  EmergencyPhoneOwner?: string;
  Email: string;
  WorkPhone?: string;
  WorkPlace?: string;
  Profession?: string;
  Country?: string;
  City?: string;
  County?: string;
  Address: string;
  DrivingClasses?: any;
  DrivingLicenseNumber: string;
  DrivingLicenseYear: string;
  IsAdditionalDriver: boolean;
  LocationSite: string;
  Code: string;
  IsActive?: boolean;
  InBlackList?: boolean;
  Balance: number;
}

export class CustomerModel {
  Name: string = "";
  Surname: string = "";
  TCNumber: string = "";
  PassportNumber: string = "";
  Gender: string = "";
  BirthDate: string = "";
  BirthPlace: string = "";
  BloodGroup: string = "";
  MotherName?: string = "";
  FatherName?: string = "";
  FirstPhone: string = "";
  EmergencyPhone?: string = "";
  EmergencyPhoneOwner?: string = "";
  Email: string = "";
  WorkPhone: string = "";
  WorkPlace: string = "";
  Profession?: string = "";
  Country?: string = "";
  City?: string = "";
  County?: string = "";
  Address: string = "";
  DrivingClasses?: any;
  DrivingLicenseNumber: string = "";
  DrivingLicenseYear: string = "";
  IsAdditionalDriver: boolean = false;
  LocationSite: string = "";
  Code: string = "";
  IsActive?: boolean = true;
  InBlackList?: boolean = false;
  Balance: number = 0;
  CreatedAt: Date = new Date();
}
